// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateBlogInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateProjectInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	UserID      string `json:"userID"`
}

type CreateResumeInput struct {
	Title       string `json:"title"`
	Description string `json:"description"`
	Category    string `json:"category"`
}

type CreateUserInput struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateBlogInput struct {
	Title   *string `json:"title,omitempty"`
	Content *string `json:"content,omitempty"`
}

type UpdateProjectInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	UserID      *string `json:"userID,omitempty"`
}

type UpdateResumeInput struct {
	Title       *string `json:"title,omitempty"`
	Description *string `json:"description,omitempty"`
	Category    *string `json:"category,omitempty"`
}

type UpdateUserInput struct {
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}
